### ISSUE TITLE
The download and git clone only include README.md

### ISSUE THREAD

**Issue by ghost** [NapoleonWils0n/bashfinder#2]

**Comment by NapoleonWils0n** [comment]
The README.md is the only visible file because the other files are dot files.
Files prefixed with a . dont show up in the Finder

If you do an ls -a in the git directory you will see the following files

.bash_aliases
.bash_macosx
.bash_profile
.inputrc
.git 

Then you move the dot files into your home directory 

mv .bash_aliases ~/.bash_aliases
mv .bash_macosx ~/.bash_macosx
mv .bash_profile ~/.bash_profile
mv .inputrc ~/.inputrc
mv .git ~/.git
