### ISSUE TITLE
Replacing dotfiles overwrites users' previous preferences.

### ISSUE THREAD

**Issue by pavellishin** [NapoleonWils0n/bashfinder#3]
```
mv .bash_profile ~/.bash_profile
```

But I have things in ~/.bash_profile that I like.

**Comment by NapoleonWils0n** [comment]
You can just copy the code from the bash profile and add it your own bash profile. Should be fine.

I only gave general instructions on how to move the files into place, as im assuming people would just add the code from the project into their existing bash_profile if they have one

Ill update the documentation to make it a bit clearer

**Comment by pavellishin** [comment]
Yeah, but it's a little confusing as to which code is relevant. For example:
- the PS1 thing in .bash_profile is completely irrelevant, but is the bash_completion stuff?
- Is anything in .inputrc related to this functionality?
- `alias ls='ls -F'` in .bash_aliases is totally irrelevant

I'd clean all of this up, leaving only the necessary lines in something like .bash_finder, and suggest doing something like `echo "[ -e .bash_finder ] && source .bash_finder" >> .bash_profile`

**Comment by NapoleonWils0n** [comment]
Hi Pavel

I try and explain which code is required for bashfinder and which is optional

The following are required 

.bash_completion
.inputrc
.bash_profile
.bash_macosx

bashfinder doesnt work without bash_completion so you have to install it in /etc/bash_completion

inputrc options:

set completion-ignore-case on 
( lets you type in lowercase so you can type desktop instead of Desktop )

set show-all-if-ambiguous on  

TAB: menu-complete  
( tab completion for menus )

"\e[Z": alias-expand-line
( shift tab to expand bash aliases )

The PS1 is how you set your command prompt
You can remove the PS1 code if you wish and add your PS1 prompt

The following arent required for bashfinder, but are useful

.bash_aliases

I have tried to comment the code as best as possible

bashfinder is really intended for advanced users who use the terminal, so im assuming people will know what bash_completion, bash_aliases and the PS1 are for. 

But everyone was a noob once, me included.
So maybe i need to make the documentation a bit more noob friendly and not assume everyone is a terminal expert.

**Comment by pavellishin** [comment]
Thank you for explaining it to me, but I would figure it out eventually - but the explanation belongs in Readme.md.

Better yet, remove anything that's not absolutely necessary from the repo. I think that most people interested in this are quite happy with the way their PS1 is set up.

**Comment by NapoleonWils0n** [comment]
HI Pavel

I wasnt trying to turn the Readme,md into a novel, or overwhelm people with too much tech info as its takes a while to write.

Im also assuming people that use the command line dont need too much spoonfeeding and will google for things that are new to them

The only things that arent needed for bashfinder to control the Finder are the PS1 and the .bash_aliases

Heres why the PS1 and .bash_aliases are included

The PS1 works with git-completion.bash to show the current state of your git working directory.
And the .bash_aliases file is include because you can use shift + tab to expand your bash aliases

bashfinder is designed so you can quickly set it up on a new Mac with bash and git completion and be able to control the Finder. And have the same PS1 prompt, so you can switch machines and still have the same terminal set up

The bash_aliases are included because they are commands i use a lot, thats all

If you already a bash_profile and bash_aliases no problem, you can just copy .bash_macosx and .inputrc to your home directory.

And then copy all the code except the PS1 from bashfinders .bash_profile to your .bash_profile
And then install bash_completion in /etc

Or you can just fork bashfinder and add your own settings

Have a look at my dotfiles which includes bashfinder and other settings and is designed to work on both Mac and Linux

https://github.com/NapoleonWils0n/dotfiles
